<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->truncate();
        DB::table('cities')->insert([
            ['name' => 'Karachi', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lahore', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Faisalabad', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Serai', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rawalpindi', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Multan', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gujranwala', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hyderabad City', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Peshawar', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Abbottabad', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Islamabad', 'state_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quetta', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bannu', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bahawalpur', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sargodha', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sialkot City', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sukkur', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Larkana', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sheikhupura', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mīrpur Khas', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rahīmyar Khan', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kohat', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jhang Sadr', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gujrat', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bardar', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kasūr', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dera Ghazi Khan', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Masīwala', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nawabshah', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Okara', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gilgit', 'state_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chiniot', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sadiqabad', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Turbat', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dera Ismaīl Khan', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chaman', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zhob', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mehra', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Parachinar', 'state_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gwadar', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kundian', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Shahdad Kot', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Harīpur', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Matiari', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dera Allahyar', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lodhran', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Batgram', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thatta', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bagh', 'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Badīn', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mansehra', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ziarat', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Muzaffargarh', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tando Allahyar', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dera Murad Jamali', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Karak', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mardan', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Uthal', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nankana Sahib', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Barkhan', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hafizabad', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kotli', 'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Loralai', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dera Bugti', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jhang City', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sahīwal', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sanghar', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pakpattan', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chakwal', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khushab', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ghotki', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kohlu', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khuzdar', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Awaran', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nowshera', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Charsadda', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Qila Abdullah', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bahawalnagar', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dadu', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Alīabad', 'state_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lakki Marwat', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chilas', 'state_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pishin', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tank', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chitral', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Qila Saifullah', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Shikarpur', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Panjgūr', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mastung', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kalat', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gandava', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khanewal', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Narowal', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khairpur', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Malakand', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vihari', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Saidu Sharif', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jhelum', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mandi Bahauddīn', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bhakkar', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Toba Tek Singh', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jamshoro', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kharan', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Umarkot', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hangu', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Timargara', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gakuch', 'state_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jacobabad', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Alpūrai', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mianwali', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mūsa Khel Bazar', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Naushahro Fīroz', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'New Mīrpur', 'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Daggar', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Eidgah', 'state_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sibi', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dalbandīn', 'state_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rajanpur', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Leiah', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Upper Dir', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tando Muhammad Khan', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Attock City', 'state_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rawala Kot', 'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Swabi', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kandhkot', 'state_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dasu', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Athmuqam', 'state_id' => 6, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
